final Map<String, String> hiIn = {
  'msg_network_err': 'Network Error',
  'msg_something_went_wrong': 'Something Went Wrong!',
  "lbl_change": "CHANGE",
  "lbl_21204034879": "21204034879",
  "lbl_select": "चुनना",
  "lbl_store_locator": "सर्वोत्तम मार्ग खोजें",
  "msg_choose_start_location": "प्रारंभ स्थान चुनें",
  "msg_choose_destination": "अंतिम स्थान चुनें",
  "lbl_map": "नक्शा",
  "msg_view_location_on": "हरित मार्ग खोजक",
  "msg_proceed_to_checkout": "Proceed to Checkout",
  "lbl_pricing_engine": "Pricing Engine",
  "msg_enter_first_name": "Enter First Name",
  "lbl_special_price": "Special price",
  "lbl_click_to_choose": "Click To Choose",
  "lbl_chatbot": "Chatbot",
  "change_language": "भाषा बदलें",
  "settings": "सेटिंग्स",
};